-- ====================================================================
-- ESQUEMA COMPLETO DE BASE DE DATOS PARA SUPABASE (POSTGRESQL)
-- Proyecto: Organizador de Notas - I.E. Inocencio Chincá
-- ====================================================================
-- INSTRUCCIONES:
-- 1. Abre el panel de tu proyecto en Supabase (https://supabase.com/dashboard)
-- 2. Ve a la pestaña "SQL Editor" en el menú lateral izquierdo
-- 3. Pega todo el contenido de este archivo y haz clic en "RUN"
-- ====================================================================

-- Limpieza preventiva si se desea reiniciar el esquema (opcional)
-- DROP TABLE IF EXISTS calificaciones CASCADE;
-- DROP TABLE IF EXISTS actividades CASCADE;
-- DROP TABLE IF EXISTS matriculas CASCADE;
-- DROP TABLE IF EXISTS cursos CASCADE;
-- DROP TABLE IF EXISTS usuarios CASCADE;

-- 1. TABLA: usuarios (docentes y estudiantes)
CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL DEFAULT '123456',
    rol TEXT NOT NULL CHECK (rol IN ('docente', 'estudiante')),
    grado TEXT,
    telefono TEXT,
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. TABLA: cursos (asignaturas escolares)
CREATE TABLE IF NOT EXISTS cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    grado TEXT NOT NULL,
    docente_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    descripcion TEXT,
    progreso INTEGER DEFAULT 75,
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. TABLA: matriculas (asociación estudiante <-> curso)
CREATE TABLE IF NOT EXISTS matriculas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    curso_id BIGINT NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(estudiante_id, curso_id)
);

-- 4. TABLA: actividades (talleres, quices, proyectos)
CREATE TABLE IF NOT EXISTS actividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    titulo TEXT NOT NULL,
    tipo TEXT DEFAULT 'Taller',
    fecha_entrega TEXT NOT NULL,
    estado TEXT DEFAULT 'Pendiente',
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. TABLA: calificaciones (registro de notas de 1.0 a 5.0)
CREATE TABLE IF NOT EXISTS calificaciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    curso_id BIGINT NOT NULL REFERENCES cursos(id) ON DELETE CASCADE,
    actividad_id BIGINT REFERENCES actividades(id) ON DELETE SET NULL,
    actividad_nombre TEXT NOT NULL,
    nota NUMERIC(3, 1) NOT NULL CHECK (nota >= 0.0 AND nota <= 5.0),
    observacion TEXT,
    fecha TEXT NOT NULL,
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 6. TABLA: reportes_individuales (observaciones y reportes individuales para estudiantes)
CREATE TABLE IF NOT EXISTS reportes_individuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id BIGINT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    docente_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    curso_id BIGINT REFERENCES cursos(id) ON DELETE SET NULL,
    periodo TEXT DEFAULT 'Primer Periodo',
    tipo TEXT DEFAULT 'Seguimiento Académico',
    titulo TEXT NOT NULL,
    contenido TEXT NOT NULL,
    recomendaciones TEXT,
    fecha TEXT NOT NULL,
    archivo_adjunto TEXT,
    archivo_nombre TEXT,
    creado_en TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ====================================================================
-- POLÍTICAS DE ACCESO (ROW LEVEL SECURITY - RLS)
-- Permitimos lectura y escritura mediante la anon key de Supabase
-- para facilitar la integración inicial de la aplicación.
-- ====================================================================

ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE cursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE matriculas ENABLE ROW LEVEL SECURITY;
ALTER TABLE actividades ENABLE ROW LEVEL SECURITY;
ALTER TABLE calificaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE reportes_individuales ENABLE ROW LEVEL SECURITY;

-- Políticas permisivas para la API
DO $$
BEGIN
    DROP POLICY IF EXISTS "Permitir todo en usuarios" ON usuarios;
    CREATE POLICY "Permitir todo en usuarios" ON usuarios FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Permitir todo en cursos" ON cursos;
    CREATE POLICY "Permitir todo en cursos" ON cursos FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Permitir todo en matriculas" ON matriculas;
    CREATE POLICY "Permitir todo en matriculas" ON matriculas FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Permitir todo en actividades" ON actividades;
    CREATE POLICY "Permitir todo en actividades" ON actividades FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Permitir todo en calificaciones" ON calificaciones;
    CREATE POLICY "Permitir todo en calificaciones" ON calificaciones FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Permitir todo en reportes_individuales" ON reportes_individuales;
    CREATE POLICY "Permitir todo en reportes_individuales" ON reportes_individuales FOR ALL USING (true) WITH CHECK (true);
END $$;

-- ====================================================================
-- DATOS INICIALES DE DEMOSTRACIÓN (SEED DATA)
-- ====================================================================

-- 1. DOCENTES
INSERT INTO usuarios (nombre, email, password, rol, grado, telefono)
VALUES
    ('Carlos Andrés Mejía', 'docente@institucion.edu.co', '123456', 'docente', NULL, '310 123 4567'),
    ('Laura Sánchez', 'laura.sanchez@institucion.edu.co', '123456', 'docente', NULL, '311 234 5678'),
    ('Jorge Luis Ramírez', 'jorge.ramirez@institucion.edu.co', '123456', 'docente', NULL, '312 345 6789'),
    ('María Fernanda Ortiz', 'maria.ortiz@institucion.edu.co', '123456', 'docente', NULL, '313 456 7890'),
    ('Andrés Felipe López', 'andres.lopez@institucion.edu.co', '123456', 'docente', NULL, '314 567 8901')
ON CONFLICT (email) DO NOTHING;

-- 2. ESTUDIANTES
INSERT INTO usuarios (nombre, email, password, rol, grado, telefono)
VALUES
    ('María José Pérez', 'maria.perez@estudiante.edu.co', '123456', 'estudiante', '10°A', '320 111 2233'),
    ('Juan Esteban Gómez', 'juan.gomez@estudiante.edu.co', '123456', 'estudiante', '11°A', '320 222 3344'),
    ('Valentina Rodríguez', 'valentina.rodriguez@estudiante.edu.co', '123456', 'estudiante', '11°B', '320 333 4455'),
    ('Andrés Felipe Torres', 'andres.torres@estudiante.edu.co', '123456', 'estudiante', '10°B', '320 444 5566'),
    ('Laura Camila Rojas', 'laura.rojas@estudiante.edu.co', '123456', 'estudiante', '10°C', '320 555 6677'),
    ('Santiago Morales', 'santiago.morales@estudiante.edu.co', '123456', 'estudiante', '10°A', '320 666 7788'),
    ('Daniela Castro', 'daniela.castro@estudiante.edu.co', '123456', 'estudiante', '11°A', '320 777 8899'),
    ('Mateo Vargas', 'mateo.vargas@estudiante.edu.co', '123456', 'estudiante', '11°B', '320 888 9900')
ON CONFLICT (email) DO NOTHING;

-- 3. CURSOS
INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Matemáticas', '10°A', id, 'Álgebra, trigonometría y funciones', 85
FROM usuarios WHERE email = 'docente@institucion.edu.co'
ON CONFLICT DO NOTHING;

INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Ciencias Naturales', '10°B', id, 'Ecosistemas, biología y conservación', 78
FROM usuarios WHERE email = 'laura.sanchez@institucion.edu.co'
ON CONFLICT DO NOTHING;

INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Física', '11°A', id, 'Mecánica clásica, electricidad y ondas', 90
FROM usuarios WHERE email = 'jorge.ramirez@institucion.edu.co'
ON CONFLICT DO NOTHING;

INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Química', '11°B', id, 'Reacciones químicas, estequiometría y laboratorio', 82
FROM usuarios WHERE email = 'maria.ortiz@institucion.edu.co'
ON CONFLICT DO NOTHING;

INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Tecnología e Informática', '10°C', id, 'Lógica de programación y desarrollo web', 75
FROM usuarios WHERE email = 'andres.lopez@institucion.edu.co'
ON CONFLICT DO NOTHING;

INSERT INTO cursos (nombre, grado, docente_id, descripcion, progreso)
SELECT 'Inglés', '10°A', id, 'Gramática aplicada, vocabulario y comprensión lectora', 88
FROM usuarios WHERE email = 'docente@institucion.edu.co'
ON CONFLICT DO NOTHING;

-- 4. MATRÍCULAS (asociar estudiantes a cursos de su grado)
INSERT INTO matriculas (estudiante_id, curso_id)
SELECT u.id, c.id
FROM usuarios u
CROSS JOIN cursos c
WHERE u.rol = 'estudiante' AND u.grado = c.grado
ON CONFLICT (estudiante_id, curso_id) DO NOTHING;

-- 5. ACTIVIDADES ESCOLARES
INSERT INTO actividades (curso_id, titulo, tipo, fecha_entrega, estado)
SELECT c.id, 'Taller: Ecuaciones cuadráticas', 'Taller', '22 ago. 2026', 'Pendiente'
FROM cursos c WHERE c.nombre = 'Matemáticas' AND c.grado = '10°A'
ON CONFLICT DO NOTHING;

INSERT INTO actividades (curso_id, titulo, tipo, fecha_entrega, estado)
SELECT c.id, 'Laboratorio: Reacciones químicas', 'Laboratorio', '25 ago. 2026', 'Pendiente'
FROM cursos c WHERE c.nombre = 'Química' AND c.grado = '11°B'
ON CONFLICT DO NOTHING;

INSERT INTO actividades (curso_id, titulo, tipo, fecha_entrega, estado)
SELECT c.id, 'Quiz: Electricidad y Magnetismo', 'Quiz', '26 ago. 2026', 'Pendiente'
FROM cursos c WHERE c.nombre = 'Física' AND c.grado = '11°A'
ON CONFLICT DO NOTHING;

INSERT INTO actividades (curso_id, titulo, tipo, fecha_entrega, estado)
SELECT c.id, 'Proyecto: Cuidado del ambiente escolar', 'Proyecto', '28 ago. 2026', 'Calificado'
FROM cursos c WHERE c.nombre = 'Ciencias Naturales' AND c.grado = '10°B'
ON CONFLICT DO NOTHING;

-- 6. CALIFICACIONES
INSERT INTO calificaciones (estudiante_id, curso_id, actividad_nombre, nota, observacion, fecha)
SELECT u.id, c.id, 'Taller: Funciones lineales', 4.5, 'Excelente desempeño y claridad procedimental', '18/08/2026'
FROM usuarios u, cursos c
WHERE u.email = 'maria.perez@estudiante.edu.co' AND c.nombre = 'Matemáticas'
ON CONFLICT DO NOTHING;

INSERT INTO calificaciones (estudiante_id, curso_id, actividad_nombre, nota, observacion, fecha)
SELECT u.id, c.id, 'Quiz: Ondas y sonido', 4.2, 'Buen análisis de frecuencias y teoría', '17/08/2026'
FROM usuarios u, cursos c
WHERE u.email = 'juan.gomez@estudiante.edu.co' AND c.nombre = 'Física'
ON CONFLICT DO NOTHING;

INSERT INTO calificaciones (estudiante_id, curso_id, actividad_nombre, nota, observacion, fecha)
SELECT u.id, c.id, 'Laboratorio: Ácidos y Bases', 4.8, 'Informe impecable y manejo de reactivos seguro', '16/08/2026'
FROM usuarios u, cursos c
WHERE u.email = 'valentina.rodriguez@estudiante.edu.co' AND c.nombre = 'Química'
ON CONFLICT DO NOTHING;

INSERT INTO calificaciones (estudiante_id, curso_id, actividad_nombre, nota, observacion, fecha)
SELECT u.id, c.id, 'Evaluación: Ecosistemas', 3.9, 'Comprende los conceptos clave, repasar niveles tróficos', '15/08/2026'
FROM usuarios u, cursos c
WHERE u.email = 'andres.torres@estudiante.edu.co' AND c.nombre = 'Ciencias Naturales'
ON CONFLICT DO NOTHING;

-- 7. REPORTES INDIVIDUALES
INSERT INTO reportes_individuales (estudiante_id, docente_id, curso_id, periodo, tipo, titulo, contenido, recomendaciones, fecha)
SELECT 
    e.id, 
    d.id, 
    c.id, 
    'Primer Periodo', 
    'Seguimiento Académico', 
    'Informe de avance cognitivo y desempeño en matemáticas', 
    'María José demuestra un gran dominio en el razonamiento lógico, resolución de problemas algebraicos y participación constructiva en clase. Trabaja con entusiasmo y colabora con sus compañeros.', 
    'Continuar fortaleciendo ejercicios de aplicación práctica y mantener el orden en el cuaderno de trabajo.', 
    '19/08/2026'
FROM usuarios e, usuarios d, cursos c
WHERE e.email = 'maria.perez@estudiante.edu.co' 
  AND d.email = 'docente@institucion.edu.co' 
  AND c.nombre = 'Matemáticas'
ON CONFLICT DO NOTHING;

INSERT INTO reportes_individuales (estudiante_id, docente_id, curso_id, periodo, tipo, titulo, contenido, recomendaciones, fecha)
SELECT 
    e.id, 
    d.id, 
    c.id, 
    'Primer Periodo', 
    'Felicitación y Mérito', 
    'Felicitación por rendimiento destacado en laboratorio', 
    'Valentina ha demostrado un riguroso manejo de los protocolos de seguridad y una capacidad analítica sobresaliente en los informes de laboratorio de química.', 
    'Se le anima a postularse como monitora de laboratorio y participar en las olimpiadas de ciencias.', 
    '18/08/2026'
FROM usuarios e, usuarios d, cursos c
WHERE e.email = 'valentina.rodriguez@estudiante.edu.co' 
  AND d.email = 'docente@institucion.edu.co' 
  AND c.nombre = 'Química'
ON CONFLICT DO NOTHING;

